# Goal: The entire plan to be executed
plan_msgs/Plan plan
---
# Result: The final outcome of the entire plan
bool success
string message
---
# Feedback: Aggregated status of all skills in the current timestep
int32 current_timestep
plan_msgs/SkillFeedback[] skill_statuses